### ISSUE TITLE
[Feature] Proxmox integration via API Key

### ISSUE THREAD

**Issue by dariuszszyc** [gnmyt/Nexterm#60]
### General

- [X] My feature does not exist in the latest version of Nexterm.
- [X] I have checked that my feature has not been suggested by anyone else.

### Your Idea

Hello,

I tried to connect to Proxmox, but since I have 2-factor auth - it doesn't work.
I suggest adding possibility to connect via API key, instead of just username & pass.

**Comment by gnmyt** [comment]
Hi, using API tokens instead of username/password authentication was also what I had [originally planned](https://github.com/gnmyt/Nexterm/commit/6d26361ce8986057927f77763f17a983010d7682). However, I think that direct websocket connections to servers that use tokens are getting blocked. At least that's the experience I had after 3 hours of debugging.

If you find a way to connect to the Proxmox websockets with API tokens, I would be happy to hear how. For now though, I think it's better to create a new user without 2FA and a strong password.

**Comment by gnmyt** [comment]
I'm closing this issue for now but if you find a solution for the problem, feel free to re-open this issue. :)

**Comment by dariuszszyc** [comment]
Not an expert, but can't you use HTTP to fetch all LXC and KVM.
Then you can use URL like this to iframe the console:
`https://192.168.1.XXX:8006/?console=lxc&novnc=1&vmid=id_of_lxc_kvm&vmname=name&node=pve_node`

I may be totally wrong though
